Splitting the func islepton and updating test
N3PDF/pineko pull request #31
Opened 2022-07-15 07:48 UTC by andreab1997

This is just a minor change to #30 due to @AleCandido suggestions.

2022-07-15 09:18 UTC, felixhekhorn commented on tests/test_check.py
> +    lumi.append([(-12, 1, 2.0), (-13, 1, 5.0)])
don't use append (`lumi` would still become crazy) - construct a new one

2022-07-18 09:03 UTC, felixhekhorn requested changes

2022-07-18 09:03 UTC, felixhekhorn commented on tests/test_check.py
> +    new_lumi.append([(1, 1, 4.0), (2, 11, 3.0)])
Same as before: let's make sane tests (such that if we ever implement a sanity check they would still pass ...); e.g.
- rename `lumi` -> `lumi_second`
- rename `new_lumi` -> `lumi_first`
- you can keep the crazy case, but just create a dedicated variable which has the thing clearly written, e.g. `lumi_crazy`
- and then check in FONLL-C *all* variables (all returning `False`)

2022-07-19 09:13 UTC, felixhekhorn approved these changes

2022-07-19 11:36 UTC, andreab1997 commented
@AleCandido Can this be merged?

2022-07-19 14:02 UTC, AleCandido approved these changes

2022-07-19 14:58 UTC, merged